JSON and HTML Output
ibbis-bio/common-mechanism pull request #24
Opened 2024-12-11 07:43 UTC by MichaelBarnett

## Background
Updates the output format potential for Commec, but centralising output Screen Data into a structure of Dataclasses, which are ultimately output as a JSON compatible format, and HTML visualisation.

## Changes
- Overhauls internal state by introducing ScreenData, a hierarchy of dataclasses, which stores the current information pertaining to a screen - which includes multiple Query handling.
- Includes an HTML output to visualise the outputs of Commec Screen.
- Extremely verbose queries which hit thousands of identical hits and regions, now collapse into more - human enjoyable formats.
- Much more control on the logic of how each step affects the overall Commec outcome.

### Bug fixes
- Fixed a bug relating to yaml --resume behaviour not correctly updating the existing db_dir value from yaml, when not overriding from cli.

### New features
- New HTML output file.
- New JSON output file.

### Breaking changes 
- Should be backwards compatible with main.

## Relevant logs, error messages, etc.
- Note, we still have issues in indexing for AA/Nucleotide/HMMSCAN indexing at the query bp level. Also doesn't yet address pre-existing pytaxonkit failure issue.
- When an exception is raised, an HTML and JSON will still be attempted to be written, which may create verbose error messages.
- Increases Commec time by a factor of 2 for pythonic check_X components, due to the duplicated logic. Plenty of room for improvement in speed here.

2025-01-13 21:30 UTC, alexanian requested changes
not finished, but here's a partial review to get started looking at

2025-01-13 21:30 UTC, alexanian commented on commec/tools/fetch_nc_bits.py
> +#!/usr/bin/env python3
We still have `fetch_nc_bits` in `commec.screeners`,  I tentatively feel like it belongs more in screeners than tools, but don't really care as long as we consolidate.

2025-01-13 21:30 UTC, alexanian commented on commec/tools/blast_tools.py
> +    #    for next, j in enumerate(df.index[top + 1:], start=top + 1):  # compare to each below
```suggestion
```
Remove in this PR? (seems like something to test, but don't want to merge to main)

2025-01-13 21:30 UTC, alexanian commented on commec/tools/blast_tools.py
> +            raise DatabaseValidationError(f"Mandatory screening files with {filename}* not found.")
```suggestion
```
Duplicate of logic above (which is just formatted differently... probably a merge error)

2025-01-13 21:30 UTC, alexanian commented on commec/config/query.py
> +        self.non_coding_regions : list[list[int]] = [[]]
Does it make sense to implement this as a `list[Tuple[int, int][` instead? I realize we're never going to have more than the start and end coordinate

2025-01-13 21:30 UTC, alexanian commented on commec/config/query.py
> +            nc_pos += region_length
Do we reference these anywhere at present? Might make sense to put into the next PR?

2025-01-13 21:30 UTC, alexanian commented on commec/config/query.py
> +            output += self.raw[start-1:end]
Can you add a comment explaining why the index adjustment?

2025-01-13 21:30 UTC, alexanian commented on commec/config/query.py
> +        self.raw : list[SeqRecord] = []
`raw` feels like a slightly vague name, maybe `query_sequences` ?

2025-01-13 21:30 UTC, alexanian commented on commec/config/query.py
> +            output += self.raw[start-1:end]
Also should probably change to
```    return ''.join(self.raw[start-1:end] for start, end in self.non_coding_regions)```
because Python allocates memory for each `+=`

2025-01-13 21:30 UTC, alexanian commented on commec/screen.py
> +from commec.utils.json_html_output import generate_html_from_screen_data
I feel a big confused about the HTML being in `utils` but the JSON being in `config`?

I wonder if `config` --> `io`, and then we have `commec.io.parameters`, `commec.io.html_output`, `commec.io.json_output`, and then move `screen_tools` under `tools`?

2025-01-13 21:30 UTC, alexanian commented on commec/screen.py
> +            self.screen_data.commec_info.benign_synbio_database_info = self.database_tools.benign_cmscan.get_version_information()
The length of these lines / variable names is sort of hard for me to read. Iwonder if we can get a few easy wins like this:
```suggestion
        self.screen_data.commec_info.biorisk_version_info = self.db_tools.biorisk_hmm.get_version_info()

        if self.params.do_protein_screen:
            self.screen_data.commec_info.aa_version_info = self.db_tools.regulated_protein.get_version_info()

        if self.params.do_nucleotide_screen:
            self.screen_data.commec_info.nt_version_info = self.db_tools.regulated_nt.get_version_info()

        if self.params.do_benign_screen:
            self.screen_data.commec_info.benign_aa_version_info = self.db_tools.benign_hmm.get_version_info()
            self.screen_data.commec_info.benign_rna_version_info = self.db_tools.benign_blastn.get_version_info()
            self.screen_data.commec_info.benign_synbio_version_info = self.db_tools.benign_cmscan.get_version_info()
```

but also feel like maybe we have nested too close to the sun.

2025-01-13 21:30 UTC, alexanian commented on commec/screen.py
> +        self.screen_data.commec_info.date_run = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
Nice :+1:

2025-01-13 21:30 UTC, alexanian commented on commec/screen.py
> +        """ Helper function, to apply a single recommendation to the whole benign step."""
I feel like we should be extra explicit that these are modifying the recommendation for every query in the run; seems like something we could forget and get confused by when we're trying to enable multiquery

2025-01-13 21:30 UTC, alexanian commented on commec/screen.py
> +        self.scripts_dir : str = os.path.dirname(__file__) # Legacy.
Do we use this anywhere?
```suggestion
```

2025-01-13 21:30 UTC, alexanian commented on commec/screen.py
> +    def __del__(self):
citation: talking to an LLM, [this stackoverflow](https://stackoverflow.com/questions/40536821/python-enter-exit-vs-init-or-new-del), but I think we might want to use `__exit__` and define a `_cleanup` method that is called from within it, rather than using `__del__` (which is about garbage collection)?

2025-01-14 00:33 UTC, alexanian commented on commec/screen.py
> +    def __del__(self):
AIUI `__enter__` and `__exit__` only get called from a context manager, so we'd need to do something like:
```
class Screen:
    def __enter__(self):
        return self
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        # current __del__ logic

def main():
    with Screen() as screen:
        screen.run(args)
```

2025-01-14 00:33 UTC, alexanian commented on commec/config/json_io.py
> +def guess_domain(search_string : str) -> str:
We only call this from `check_biorisk`, should we put it in there instead?

2025-01-14 00:33 UTC, alexanian commented on commec/config/json_io.py
> +class CommecScreenStep(StrEnum):
Restructuring proposal (related to the `config` --> `io`) that I proposed before; I think we should separate out the enums / bits holding the actual progress of screening from the JSON serialization logic.

What if we did `screeners` --> `screening` and moved some of these data classes in there?

2025-01-14 00:33 UTC, alexanian commented on commec/config/json_io.py
> +class QueryData:
Maybe move this and `ScreenData` into something like `screening/results.py` and then call them something like `QueryRun` and `ScreenRun`? (with just `Data` it's not obvious to me that these are output vs. input data containers)

2025-01-18 22:09 UTC, MichaelBarnett commented on commec/screen.py
> +    def __del__(self):
I came across this exact same stackoverflow thread when writing this code, and actually did try using __exit__ and using _with_ context, however after testing with exceptions / and forcing stops, I got the most consistent successful calling of the delete logic with the __del__ override - which was surprising as it went against somewhat what was being said, but makes sense from a memory perspective, especially as the screen instances has a very clear life-time and scope, and there is only ever a single reference to it.
 I can try those tests again to see if we can get the same or more expected behaviour with __exit__.

2025-01-20 22:28 UTC, alexanian reviewed
running slowly through...

2025-01-20 22:28 UTC, alexanian commented on commec/config/json_io.py
> +    summary_info : CommecSummaryStatistics = field(default_factory=CommecSummaryStatistics)
I think we should remove this here, yeah

2025-01-20 22:28 UTC, alexanian commented on commec/config/json_io.py
> +    # non_coding_regions : list[list[int]] = field(default_factory=list)
```suggestion
```
Assuming we don't want this here?

2025-01-20 22:28 UTC, alexanian commented on commec/config/json_io.py
> +class CommecScreenStep(StrEnum):
In particular, I feel like `Hit` + `Hit Description` belong together, and `CommecRecommendation` (propose rename `ScreenOutcome` or `ScreenStatus`) and its attendant bits go together in another module?

2025-01-20 22:28 UTC, alexanian commented on commec/config/json_io.py
> +        return False
```suggestion
        return hits_is_updated
```

2025-01-20 22:28 UTC, alexanian commented on commec/config/json_io.py
> +            return False
Does this imply that hits should be a `dict` indexed by name, rather than a list? It feels like we're treating them that way

2025-01-20 22:28 UTC, alexanian commented on commec/config/json_io.py
> +            search_term = query_name[:-2]
hm; I find myself getting a bit tangled on the overlap between `query.py` (custom class we have written specifically to store input to `screen`) and `QueryData`, which based on this, can hold protein or nucleotide queries... I wonder if we should be storing the translations more explictly?

2025-01-25 06:36 UTC, MichaelBarnett commented on commec/screen.py
> +            self.screen_data.commec_info.benign_synbio_database_info = self.database_tools.benign_cmscan.get_version_information()
hmm despite nesting being so fun, I see you point. I did a small work-around with a local variable assignment, for readibilities sake. But perhaps that too is not dealing with the original problem. I would rather have obtusely long nested paths, rather than compromise by shorthanding individual variable names however.

2025-01-25 06:38 UTC, MichaelBarnett commented on commec/config/json_io.py
> +def guess_domain(search_string : str) -> str:
not a bad idea really, especially as we hope to be rid of it with updated biorisk databases in the future.

2025-01-25 06:43 UTC, MichaelBarnett commented on commec/config/json_io.py
> +class QueryData:
At the very least a rename is in order as discussed, and perhaps removing any erroneous info we don't wish to be reported on. As you know this has the single purpose of an output representation container for a single query. I like QueryResult and ScreenResult. I suppose I've used data in the past as it aligns with 'State'.

2025-01-27 21:34 UTC, alexanian commented
based on our discussion last week, a proposal for reorganizing modules (that does not yet separate out the state-storage vs. output-handling parts of json_io) : https://github.com/ibbis-bio/common-mechanism/commit/db30b3ea9ce02241c30806a5cd26ba49fb3d9887

2025-02-12 23:44 UTC, alexanian commented
A few requests from more end-to-end testing:

* Add some guard clauses in `__del__` (specifically: check if screen_io is `None`, since if so the run failed on initialization and the JSON/HTML output should not be produced; right now this leads to an error) 
* Make sure tracebacks are captured in the `log` or `screen` file; should be easy to replicate by passing in an invalid database directory
* We should be referencing `template.html` as a package resource, not a filepath, should be doing a `importlib.resources.files("commec")` call rather than `template = Template(filename="commec/utils/template.html")`
* Should not skip the benign search in the case of the following:
```
            "recommendation": {
                "screen_status": "Flag",
                "biorisk_status": "Warning",
                "protein_taxonomy_status": "Flag",
                "nucleotide_taxonomy_status": "Pass",
                "benign_status": "Skip"
            },
```
* Also, we currently still produce a `.screen` file, but it seems almost exactly the same as the `log` file (except the log contains a dump of the input FASTA; probably not needed?) and is not accurate. For example, for the run above, the `.screen` file was:
```
>> STEP 1: Checking for biorisk genes...
		 --> Biorisks: Regulated genes not found, PASS

 STEP 1 completed at 2025-02-12 21:03:25
 >> STEP 2: Checking regulated pathogen proteins...
 STEP 2 completed at 2025-02-12 21:40:18
 >> STEP 3: Checking regulated pathogen nucleotides...
Checking protein hits in: /mnt/data/home/ec2-user/analysis/functional-test-json/2025-02-11/BBa_I766605-YopH-EE.nr.blastx
Protein hits found for BBa_I766605_YopH-EE_under, fetching nt regions not covered by a 90% ID hit or better
Identified noncoding regions [1414-1641]
		 --> no top hit exclusive to a regulated pathogen: PASS

	...no regulated hits

 STEP 3 completed at 2025-02-12 22:36:45
>> STEP 4: Checking any pathogen regions for benign components...
	...no regulated regions to clear

>> STEP 4 completed at 2025-02-12 22:36:45
>> COMPLETED AT 2025-02-12 22:36:45
```
which doesn't match the JSON.

2025-04-08 19:15 UTC, closed without merging